apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: inference-canary-pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: 30s
  selector:
    namespaces:
      - workload
    labelSelectors:
      app: inference-service
      track: canary